### ISSUE TITLE
Parallel processing of objects

### ISSUE THREAD

**Issue by plepe** [plepe/pgmapcss#102]
Currently, objects are processed serial, so that a set tag statement on a parent (or otherwise related object) can not be read by parent_tag(). E.g.

```css
relation[type=route][route=tram] {
  set .foo = bar;
}
relation[type=route][route=tram] > way {
  text: parent_tag(".foo");
}
```

With the implementation of this issue, the first statement should be executed for all (possible) parent objects, and then the second for all the ways.
