### ISSUE TITLE
Globals

### ISSUE THREAD

**Issue by plepe** [plepe/pgmapcss#104]
It would be great  if it would be possible to use (global) variables. Similar to [less](http://lesscss.org/) these could be prefixed by '@'. So that a variable gets global, it should first be used in global space. Example (similar to #77, but rather extending it):
```css
/* initialize variable @list with an empty list, making it global */
@list: list();

/* process all peaks ordered by elevation downward */
node[natural=peak]:order-numerical(ele, desc) {
  /* to @list append the name of the current map feature */
  @list: append(@list, tag("name"));
}

/* print current @list to stderr, which should be the names of all peaks 
 * in current bounding box, ordered by elevation downward */
debug(@list);
```

The following things need to be implemented:
- [ ] variables, which are names prepended by @ 
- [ ] check reserved names
- [ ] statements in global space, even without destination where the result should go to (like the `debug()` in the last row).
- [ ] use variables inside of eval statements
