### ISSUE TITLE
Optimize eval functions with fixed result

### ISSUE THREAD

**Issue by plepe** [plepe/pgmapcss#112]
When eval functions have a fixed result (e.g. `2+2`), pgmapcss uses this fixed result, just like as if the final value would have been given.

E.g.:
```css
node {
  foo: 2+2;
  foo: 4;
}
```
will both compile into
```python
current['properties']['foo'] = '4'
```

When using a property where the value is checked/modified before assigning, the check/modification could be done at compile time.

E.g.
```css
way {
  color: red;
  color: concat('r', 'e', 'd');
}
```
will compile into
```python
current['properties']['color'] = '#ff0000';
current['properties']['color'] = check_color('red');
```

Therefore, for every map feature which matches this rule the `check_color()` function will be called, which is not necessary.
