### ISSUE TITLE
Icons: load icons from URLs

### ISSUE THREAD

**Issue by plepe** [plepe/pgmapcss#52]
E.g.

``` css
node {
  icon-image: "https://github.com/species/josm-preset-wheelchair/raw/master/kerb_unknown.png";
}
```
